spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    #初始化dispatcherServlet，默认-1未开启，0及以上为开启
    static-path-pattern: /static/**
    servlet:
      load-on-startup: 1
server:
  port: 9999
  servlet:
    context-path: /rop
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.richeninfo.entity.mapper.entity
  configuration:
    mapUnderscoreToCamelCase: false
#showSql
logging:
  level:
    #配置日志打印级别
    root: info
    org:
      mybatis: debug
    com:
      sxl:
        mybatispluss:
          mapper: debug
ftp.info:
  server: 10.196.26.178  #FTP服务器地址
  port: 21    #FTP端口号
  username: ftpdir    #FTP用户名
  password: Rh20Gw23#Wx    #FTP密码
  encoding: UTF-8   #FTP文件编码
  base-path: /   #FTP默认根路径
  systemSymbols: /
  size: 200Mb   #上传文件大小限制，由应用控制（需要有返回提示）
  pattern: .gif|.jpg|.jpeg|.png|.xls|.doc|.xlsx|.docx|.pdf|.zip|.rar|.txt|.mp4|.svg|.avif|.webp  #允许的扩展名配置，不限制则配置all
  show-path: /img/ftppic
# 设置文件上传大小限制
spring.servlet.multipart.max-file-size: 500MB
spring.servlet.multipart.max-request-size: 500MB