spring:
  redis:
    host: 121.40.205.162
    password: h1e2j3i4a5o6s7h8o9u0!@#$%^&*
    port: 6379
  master:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://121.40.205.162:3306/weixin?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: richen123.
    #activemq配置
  activemq:
    broker-url: tcp://47.111.174.33:61616  #activeMQ的ip和端口号
    user: richen   #activeMq账号
    password: Richen123info. #activeMq密码
    non-blocking-redelivery: false # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    send-timeout: 0 # 等待消息发送响应的时间。设置为0等待永远。
    in-memory: true
    queue-name: proemMQ  # queue队列的名称
    topic-name: examTopic  # topic队列的名称
    pool:
     enabled: true # 启用连接池
     max-connections: 100 # 最大连接数
     idle-timeout: 30000 # 空闲的连接过期时间，默认为30秒
#文件上传地址
basePath: https://richeninfo.com
filePath: /opt
#能开平台相关配置信息
#正式地址product
nengKai:
  ip: 211.136.111.133
  config_context: /openapi/secret
  appCode: A0000479
  apk_new: ZK2KFvG5wn/pXtUEAeUsv7DWks2eXbU+
  apk: KbYv6fJRH4pUruNM+2HvTCm2L+nyUR+K
  securityUrl: http://211.136.111.133/open/security
  openapiUrl: http://211.136.111.133/open/service



