/*
 * Copyright (c) RICHENINFO [2024]
 * Unauthorized use, copying, modification, or distribution of this software
 * is strictly prohibited without the prior written consent of Richeninfo.
 * https://www.richeninfo.com/
 */
package com.richeninfo.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AssertionQryUIDWS", targetNamespace = "http://login.10086.cn")
public interface AssertionQryUIDWS {

	/**
	 * 
	 * @param request
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "getAssertInfoByUID")
	@WebResult(name = "response", targetNamespace = "")
	@RequestWrapper(localName = "getAssertInfoByUID", targetNamespace = "http://login.10086.cn", className = "com.richeninfo.wsdl.GetAssertInfoByUID")
	@ResponseWrapper(localName = "getAssertInfoByUIDResponse", targetNamespace = "http://login.10086.cn", className = "com.richeninfo.wsdl.GetAssertInfoByUIDResponse")
	public String getAssertInfoByUID(
			@WebParam(name = "request", targetNamespace = "") String request);

}
